### PR TITLE
Upgrade to Django 1.8.6.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by akatsoulas** [comment]
@johngian can you please test this locally?

**Comment by johngian** [comment]
I am getting this error.

```
AttributeError: 'PinningMasterSlaveRouter' object has no attribute 'allow_migrate'
```

**Comment by johngian** [comment]
I suggest since this is not a security release we keep to the previous version until DB router gets fixed.

**Comment by akatsoulas** [comment]
Same here, this is fixed in the development version of 1.8.7. I would suggest to wait until then. I am adding an issue as a reminder and closing this one.

**Pull request closed without merging**
