### PR TITLE
Add flag to track devices that are actively foxfooding.

### PR DESCRIPTION
**Pull request by johngian**

### CODE REVIEW

**Comment by akatsoulas** [comment]
This needs a rebase. Also there is already an `is_foxfooding` flag in `Build` model. If we are proceeding with this, we need to remove the other.

**Comment by johngian** [comment]
This is a different flag. We are going to use this to flag users who are actively foxfooding.

**Comment by johngian** [comment]
@akatsoulas PR updated

**Comment by johngian** [comment]
@akatsoulas @comzeradd r?

**Comment by akatsoulas** [comment]
Looks good. Minor comment, I would suggest to change the naming to one of the two `is_foxfooding` flags to avoid confusion. r+wc :hamburger:

**Pull request merged**
