### PR TITLE
Fix issues with staticfiles

### PR DESCRIPTION
**Pull request by johngian**
- Serve missing fonts locally

### CODE REVIEW

**Comment by comzeradd** [comment]
We won't use emberjs after all. You may remove the relevant code lines from `app.js`. Sorry for the confusion.

**Comment by akatsoulas** [comment]
@johngian let's remove the last commit and merge this. r+wc

**Comment by comzeradd** [comment]
After the work that has been done at #9 this PR is obsolete.

**Comment by johngian** [comment]
This PR was opened before #9 
@comzeradd 
I suggest we merge this and rebase it in your PR.

**Comment by johngian** [comment]
@akatsoulas PR updated

**Pull request merged**
