### PR TITLE
Wrap GA in DNT conditional

### PR DESCRIPTION
**Pull request by comzeradd**
Make sure we don't hit GA for users who have "Do Not Track" enabled. This is the same implementation [bedrock has](https://github.com/mozilla/bedrock/commit/b5735136df5a4326982f98ea56a7d68500f2c2ed).

### CODE REVIEW

**Comment by comzeradd** [comment]
@johngian r?

**Comment by johngian** [comment]
Please make sure that `build` GA events work after that change.

**Comment by johngian** [comment]
r+wc

**Comment by comzeradd** [comment]
The build event will keep working if the user doesn't have DNT enabled. I just wrapped this piece of code too, so we don't get undefined error for the `ga()` function.

**Pull request merged**
