### PR TITLE
Fix dashboard links for reporting bugs

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by comzeradd** [comment]
@akatsoulas r?

**Comment by akatsoulas** [comment]
@comzeradd sure. Could you please comment what this PR is about?

**Comment by comzeradd** [comment]
The params are used to prepopulate the Bugzilla form. It seems we were using the wrong values.

**Comment by akatsoulas** [comment]
not much to review here, code looks good - haven't tested this though. r+

**Pull request merged**
