### PR TITLE
Rebrand Participation Hub

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by comzeradd** [comment]
@johngian r?

**Comment by johngian** [comment]
@comzeradd Things got busy lately with the rest of the projects and I haven't found the time to review that one yet. I suggest you ping someone else preferably someone more dedicated to UI since the changes applied are mostly changing the frontend.

**Comment by comzeradd** [comment]
I don't think it makes much sense for this PR to get reviewed by someone not familiar with the project. It will take more time to get familiar with the codebase than to actually review it. Besides this PR is mostly deletions, rather than additions.

Unless @ppapadeas has time to have a look, I suggest we wait until we have time to review.

**Comment by akatsoulas** [comment]
Closing this because the site going to be decommissioned soon.

**Pull request closed without merging**
