### PR TITLE
Various UI and copy fixes

### LINKED ISSUE #94: Copy Edit: Adjust sentence on first page.
Copy: "Find out how you can install Firefox OS on your device and ways to get started."

Problem: The link only sends you to installs, it doesn't tell you "how to get started". It also reads very strangely. 

Suggested edit:  "Find out how to install Firefox OS on your device!"

### PR DESCRIPTION
**Pull request by ppapadeas**
Fixes #94 , #93 , #90

### CODE REVIEW

**Comment by ppapadeas** [comment]
r+ :gb: :P

**Comment by brianking** [comment]
r++

**Comment by brianking** [comment]
r++

**Comment by comzeradd** [comment]
Closing this in favor of #105. About text has been updated completely as per #102

**Pull request closed without merging**
