### PR TITLE
Validate imei number.

### PR DESCRIPTION
**Pull request by akatsoulas**

### CODE REVIEW

**Comment by johngian** [comment]
Please fix typo in commit message.

**Comment by johngian** [comment]
For some reason the error is not rendered in form errors.

**Comment by akatsoulas** [comment]
This is happening for the whole modal and not just for the validator. This is tracked in the issues. I would suggest to merge this and fix the rendering issue on its own

**Comment by johngian** [comment]
go go go
Validator code looks OK.

**Comment by johngian** [comment]
r+

**Pull request merged**
