### PR TITLE
Highlight selected option on Contribute nav links

### LINKED ISSUE #191: Nice to have: Add selected option visual between Contribute options
- this will be a nice thing to have / maybe volunteer task
1. If you go and choose one of the contribute options you will have a menu displayed in your left side.
2. Switching between these options should also show on which you are ( on reps you have it bolded)

### PR DESCRIPTION
**Pull request by comzeradd**
- Fixes #191

### CODE REVIEW

**Comment by comzeradd** [comment]
@akatsoulas r?

**Comment by akatsoulas** [comment]
On the issue it's commented that the link should be "de-linkified" and not bold.

**Comment by akatsoulas** [comment]
Instead of setting an `active` class in each template, you could create a `helper` function which could append the `active` flag if the url is in the request.

**Comment by comzeradd** [comment]
> On the issue it's commented that the link should be "de-linkified" and not bold.

Both are mentioned. I made a UI decision to keep the link, but emphasize it.

> Instead of setting an active class in each template, you could create a helper function which could append the active flag if the url is in the request.

Yes, that was the other option. I preferred to go with this as suggested in [Jinja's documentation](http://jinja.pocoo.org/docs/dev/tricks/#highlighting-active-menu-items), to keep this change on the frontend side only. A helper template tag would be my choice if all the links were rendered dynamically.

**Comment by akatsoulas** [comment]
Closing this because the site going to be decommissioned soon.

**Pull request closed without merging**
