### PR TITLE
Devices backend/frontend changes

### PR DESCRIPTION
**Pull request by comzeradd**

### CODE REVIEW

**Comment by comzeradd** [comment]
@johngian or @akatsoulas r?

**Comment by johngian** [comment]
- Icon from device specs is missing
- Single device page with "realistic" device data seems misaligned.
  - Documentation button looks huge compared to the small comment text above
  - Model, comment and build elements have 3 different vertical positions
- Doesn't really make sense to me to have the `builds missing` text. I don't have strong opinion on that but in case we use it let's align it with the comment or with some of the elements next to this.
- Documentation picture looks kind of misaligned to me:
  - Tried different values like`margin-bottom: 5px;` and looks kind of better.

**Comment by johngian** [comment]
@akatsoulas can you take a look in the backend code?

**Comment by akatsoulas** [comment]
Sorry for commenting inside the commit :)

I haven't tested this but apart from this minor comments code looks good. r+ for the back-end

**Comment by comzeradd** [comment]
@johngian PR updated

> Icon from device specs is missing

Yes, since this is a generic comment field and not just specs, I don't think we need the icon anymore.

> Single device page with "realistic" device data seems misaligned.
>   Documentation button looks huge compared to the small comment text above
>   Model, comment and build elements have 3 different vertical positions
>   Doesn't really make sense to me to have the builds missing text. I don't have strong opinion on that but in case we use it let's align it with the comment or with some of the elements next to this.
>  Documentation picture looks kind of misaligned to me

I fixed all misalignment/size issues.

**Comment by johngian** [comment]
Please rebase once again :\

**Comment by comzeradd** [comment]
@johngian rebased

**Comment by johngian** [comment]
Mobile view looks broken.
- Documentation button is too close to build download buttons.
- Comment field is misaligned with the picture

**Comment by johngian** [comment]
I still think that single device page needs some love (eg. I think that the columns and sizes between picture, documentation and build downloads is unbalanced), but I don't have any strong opinions on that.

@comzeradd I suggest you revisit this in case you think that there some fixes in terms of UI.

**Comment by johngian** [comment]
Code look OK. r+wc

**Comment by comzeradd** [comment]
Thanks. I did some minor tweaks to fix device detail mobile view.

**Pull request merged**
