### PR TITLE
More flatpages on navbar

### PR DESCRIPTION
**Pull request by comzeradd**
- Add Foxfooding nav menu
- Add Foxfooding flatpages
- Add default flatpage template

### CODE REVIEW

**Comment by comzeradd** [comment]
@ppapadeas r?

**Comment by ppapadeas** [comment]
Shouldn't you also create the templates for the Foxfooding pages too?

**Comment by comzeradd** [comment]
I created a `flatpage.html` to be used on both of these pages.

**Comment by ppapadeas** [comment]
r+ then! :airplane:

**Pull request merged**
